PACKAGE_NAME="minibook-lid-wake"
PACKAGE_VERSION="0.1"
CLEAN="make clean"
MAKE[0]="make all KDIR=/lib/modules/$kernelver/build LLVM=1"
BUILT_MODULE_NAME[0]="minibook_lid_wake"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
